version: '3'

services:
  teamspeak-nginx:
    container_name: teamspeak-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "9987:9987/udp"
      - "9987:9987/tcp"
      - 30033:30033
    volumes:
      - ./teamspeak/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - teamspeak-local
  
  teamspeak-teamspeak:
    container_name: teamspeak-teamspeak
    image: teamspeak:latest
    restart: unless-stopped
    ports:
      - "9989:9987/udp"
    environment:
      TS3SERVER_LICENSE: accept
    volumes:
      - ./teamspeak/teamspeak/data:/var/ts3server/
    networks:
      - teamspeak-local

networks:
  teamspeak-local:
